apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  GATEWAY_URL: 'http://gateway:5000' #also add gateway service port
  MATH_URL: 'http://math-service:5000' #also add math service port
  STRING_URL: 'http://string-service:5000' #also add string service port
  LOG_URL: "http://log-service:5000"
