version: '1'
services:
  math-service:
    build: math_py
    env_file:
      - .env

  string-service:
    build: string_py
    env_file:
      - .env

  log-service:
    build: log_py
    env_file:
      - .env

  gateway:
    build: gateway
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - math-service
      - string-service
      - log-service
