---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer 
  selector: 
    app: gateway
  ports:
    - protocol: TCP
      port: 5000  # A “port” refers to the container port exposed by a pod or deployment
      targetPort: 5000 # “targetPort” refers to the port on the host machine that traffic is directed to
---
apiVersion: v1
kind: Service
metadata:
  name: math-service
spec:
  selector: 
    app: math-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: string-service
spec:
  selector: 
    app: string-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: log-service
spec:
  selector: 
    app: log-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
